// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD-cVoLUGszWdGfVUgGGAoOkgOUbap89w',
    appId: '1:464151302054:web:99e09e03703b31d3bc8967',
    messagingSenderId: '464151302054',
    projectId: 'test-devgram',
    authDomain: 'test-devgram.firebaseapp.com',
    storageBucket: 'test-devgram.firebasestorage.app',
    measurementId: 'G-FJF2W4T6W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcY2Y4Afv4gpoqVs7gCaFCJrpSVePFV1o',
    appId: '1:464151302054:android:92e635b706d9770cbc8967',
    messagingSenderId: '464151302054',
    projectId: 'test-devgram',
    storageBucket: 'test-devgram.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWJnm1J7pPByZK-DWINMvBZUXLMv4Vo5M',
    appId: '1:464151302054:ios:42525b8693ed8a42bc8967',
    messagingSenderId: '464151302054',
    projectId: 'test-devgram',
    storageBucket: 'test-devgram.firebasestorage.app',
    iosBundleId: 'com.devgram.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWJnm1J7pPByZK-DWINMvBZUXLMv4Vo5M',
    appId: '1:464151302054:ios:5b8bb0ca9cf47b7abc8967',
    messagingSenderId: '464151302054',
    projectId: 'test-devgram',
    storageBucket: 'test-devgram.firebasestorage.app',
    iosBundleId: 'com.example.devgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD-cVoLUGszWdGfVUgGGAoOkgOUbap89w',
    appId: '1:464151302054:web:8ea5a78fb04e85ccbc8967',
    messagingSenderId: '464151302054',
    projectId: 'test-devgram',
    authDomain: 'test-devgram.firebaseapp.com',
    storageBucket: 'test-devgram.firebasestorage.app',
    measurementId: 'G-50VZT28M2K',
  );
}
